CREATE DATABASE SALES;
USE SALES;
CREATE TABLE SALES(SALESID INT AUTO_INCREMENT PRIMARY KEY , PRODUCTS VARCHAR(100) , CATEGORY VARCHAR(200) , AMOUNT INT , DATEOFSALE DATE);
INSERT INTO SALES(PRODUCTS,CATEGORY,AMOUNT,DATEOFSALE)
VALUES
('PEN','STATIONARY','10,'2024-12-20'),
('BAG','STATIONARY',500,'2026-1-24'),
('CHARGER','ELECTRONICS',1000,'2023-11-02'),
('REMOTE','ELECTRONICS',1500,'2025-3-04'),
('HAND BAG','ASSEC',2000,'2021-4-09');
SELECT *FROM SALES;
SELECT COUNT(*)FROM SALES;
SELECT SUM(AMOUNT)FROM SALES;
SELECT MIN(AMOUNT)FROM SALES;
SELECT MAX(AMOUNT)FROM SALES;
SELECT AVG(AMOUNT)FROM SALES;
SELECT CATEGORY, SUM(AMOUNT)
FROM SALES
GROUP BY CATEGORY;