create DATABASE if NOT EXISTS shopDB;
use shopDB;
create table shop(
 studentID int auto_increment PRIMARY KEY ,  NAME VARCHAR(200),EMAIL VARCHAR (400) UNIQUE,ADDRESS VARCHAR(500)
);
INSERT INTO SHOP(NAME , EMAIL , ADDRESS)
VALUES
 ('NANSEE GUPTA','NG7905@GMAIL.COM','HINDAUN,INDIA' ),
 ('GOBAR PRASADH','RADH3IKA@GMAIL.COM', 'GZB,INDIA'),
 ('GOBAR PRASADH','FOB#RT@GMAIL.COM','NOIDA,INDIA');
SELECT * FROM SHOP;
DELETE FROM SHOP WHERE NAME='GOBAR PRASADH';