create DATABASE IF NOT EXISTS RETAILSTORE;
USE RETAILSTORE;
CREATE TABLE CUSTOMERS(
    CUSTOMERID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100)
);
CREATE TABLE ORDERS(
    ORDERID INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT VARCHAR(100),
    AMOUNT INT ,
    CUSTOMERID INT,
    FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMERS (CUSTOMERID)
);

INSERT INTO CUSTOMERS(NAME) VALUES
('SIYA'),
('NANSEE'),
('AAYUSH');

INSERT INTO ORDERS(PRODUCT,AMOUNT,CUSTOMERID) 
VALUES
('STICKERS',300,1),
('BOTTLE',500,2);

SELECT * FROM CUSTOMERS;
SELECT * FROM ORDERS;


SELECT CUSTOMERS.NAME ,ORDERS.PRODUCT , ORDERS.AMOUNT
FROM CUSTOMERS
INNER JOIN ORDERS ON CUSTOMERS.CUSTOMERID=ORDERS.CUSTOMERID;