create DATABASE IF NOT EXISTS RETAILSTORE;
USE RETAILSTORE;
CREATE TABLE CUSTOMERS(
    CUSTOMERID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100)
);
CREATE TABLE ORDERS(
    ORDERID INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT VARCHAR(100),
    AMOUNT INT ,
    CUSTOMERID INT,
    FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMERS (CUSTOMERID)
);

INSERT INTO CUSTOMERS(NAME) VALUES
('SIYA'),
('NANSEE'),
('AAYUSH'),
('NEHU'),
('JAMNA');

INSERT INTO ORDERS(PRODUCT,AMOUNT,CUSTOMERID) 
VALUES
('STICKERS',300,1),
('BOTTLE',500,2),
('NAMAK',100,3),
('GOLD CHAIN',2000000,4);



SELECT * FROM CUSTOMERS;
SELECT * FROM ORDERS;

DELETE FROM ORDERS WHERE CUSTOMERID IS NULL;

SELECT CUSTOMERS.NAME ,ORDERS.PRODUCT , ORDERS.AMOUNT
FROM CUSTOMERS
INNER JOIN ORDERS ON CUSTOMERS.CUSTOMERID=ORDERS.CUSTOMERID;

SELECT  CUSTOMERS.NAME ,ORDERS.PRODUCT , ORDERS.AMOUNT
FROM CUSTOMERS
LEFT JOIN ORDERS ON CUSTOMERS.CUSTOMERID=ORDERS.CUSTOMERID

UNION

SELECT CUSTOMERS.NAME ,ORDERS.PRODUCT,ORDERS.AMOUNT
FROM CUSTOMERS
RIGHT JOIN ORDERS ON CUSTOMERS.CUSTOMERID=ORDERS.CUSTOMERID;




