create DATABASE if NOT EXISTS shopDB;
use shopDB;
create table shop(
 studentID int auto_increment PRIMARY KEY ,  NAME VARCHAR(200),EMAIL VARCHAR (400) UNIQUE,ADDRESS VARCHAR(500)
);
INSERT INTO SHOP(NAME , EMAIL , ADDRESS)
VALUES
 ('NANSEE GUPTA','NG7905@GMAIL.COM','HINDAUN,INDIA' ),
 ('GOBAR PRASADH','RADH3IKA@GMAIL.COM', 'GZB,INDIA'),
 ('GOBAR PRASADH','FOB#RT@GMAIL.COM','NOIDA,INDIA');
SELECT * FROM SHOP;
SELECT NAME FROM SHOP; -- IS YOU WANT TO SEE A SPECIFIC COLUMN 
SELECT EMAIL FROM SHOP;
SELECT ADDRESS FROM SHOP;
SELECT DISTINCT NAME,ADDRESS FROM SHOP;--IT WILL GIVE YOU THE NON DUPLICATE DATA
SELECT*FROM SHOP WHERE ADDRESS LIKE '%NOIDA%';
SELECT*FROM SHOP WHERE NAME LIKE '%GOBAR PRASADH%' OR ADDRESS LIKE '%NOIDA%';
SELECT*FROM SHOP WHERE NAME LIKE '%GOBAR PRASADH%' AND ADDRESS LIKE '%NOIDA%';
SELECT*FROM SHOP WHERE NAME NOT LIKE '%GOBAR PRASADH%' OR ADDRESS NOT LIKE '%NOIDA%';

